#!/bin/bash
# for ((a = 1, b = 0; a < 10; a++, b++ ))
# do
# 	# echo "The next number is $a"
# 	c=$[ $a - $b ]
# 	echo "The dif bewteen a and b is $a - $b equal to $c"
# done

# var1=10
# while [ $var1 -gt 0 ]
# do
# 	echo -n "$var1 "
# 	var1=$[ $var1 - 1 ]
# done
# echo


# var1=10
# while echo $var1
# 	[ $var1 -gt 0 ]
# do
# 	echo "This is inside the loop"
# 	var1=$[ $var1 - 1 ]
# done
# echo


# var1=100
# until [ $var1 -eq 0 ]
# do
# 	echo $var1
# 	var1=$[ $var1 - 25 ]
# done


# var1=3
# until [ $var1 -eq 0 ]
# do
# 	echo "Outer loop: $var1"
# 	var2=1
# 	while [ $var2 -lt 5 ]
# 	do
# 		var3=$(echo "scale=4; $var1 / $var2" | bc)
# 		echo "     Inter loop: $var1 / $var2 = $var3"
# 		var2=$[ $var2 + 1 ]
# 	done
# 	var1=$[ $var1 - 1 ]
# done


# OLD=$IFS
# IFS=$'\n'
# for entry in $(cat /etc/passwd)
# do
# 	echo "Value in $entry"
# 	IFS=:
# 	for value in $entry
# 	do
# 		echo "    $value"
# 	done
# done


# for ((a = 1; a < 10; ++a ))
# do
# 	if [ $a -eq 5 ]
# 	then
# 		echo "The loop will break."
# 		break;
# 	else
# 		echo "A equal to $a"
# 	fi
# done


# for (( a = 1; a < 10; ++a))
# do
# 	echo "Outer loop: $a"
# 	for (( b = 1; b < 100; ++b ))
# 	do
# 		if [ $b -gt 4 ]
# 		then
# 			break 2;
# 		fi
# 		echo "      Inner loop: $b"
# 	done
# done


# for (( a = 1; a <= 5; ++a ))
# do
# 	echo "Iteration $a:"
# 	for (( b = 1; b < 3; ++b ))
# 	do
# 		if [ $a -gt 2 ] && [ $a -lt 4 ]
# 		then
# 			continue 2
# 		fi
# 		var3=$[ $a * $b ]
# 		echo "     The result of $a * $b is $var3"
# 	done
# done


for (( a = 1; a < 10; ++a))
do
	echo "The number is $a"
done >> log.txt
