#!/bin/bash
# directory=/home/xl
# 
# if [ -d $directory ]
# then
# 	echo "The $directory exists."
# 	cd $directory
# 	tree $directory
# else
# 	echo "The $directory not exists."
# fi


# location=$HOME
# file_name="sentinel"
# 
# if [ -d $location ]
# then
# 	echo "OK on the $location directory"
# 	echo "Now checking on the file, $file_name"
# 	if [ -e $location/$file_name ]
# 	then
# 		echo "OK on the file, $file_name"
# 		echo "Updating file's contents."
# 		date >> $location/$file_name
# 	else
# 		echo "File, $location/$file_name, does NOT exist."
# 		echo "Nothing to update."
# 	fi
# else
# 	echo "Directory, $location, does NOT exist."
#  	echo "Nothing to update."
# fi

# pwfile=/etc/shadow
# pwfile=/home/xl/test
# echo
# echo "Checking if you can read $pwfile..." 
# 
# if [ -f $pwfile ]
# then
# 	if [ -r $pwfile ]
# 	then
# 		echo "Displaying end of file..."
#  		tail $pwfile
# 	else
# 		echo "Sorry, read access o $pwfile is denied."
# 	fi
# else
# 	echo "Sorry, the $pwfile file does not exist."
# fi
#



# file_name=$HOME/test
# echo
# echo "Checking if $file_name file is empty..."
# echo
# 
# if [ -f $file_name ]
# then
# 	# File does exist. Check if it is empty.
# 	#
# 	if [ -s $file_name ]
#  	then
#  		echo "The $file_name file exists and has data in it."
#  		echo "Will not remove this file."
# 	 #
#  	else
#  		echo "The $file_name file exits, but is empty."
#  		echo "Deleting empty file..."
#  		rm $file_name
#  	fi
# 	#
# else
#  	echo "The $file_name file does not exist."
# fi


# if [ -O /etc/passwd ]
# if [ -O $HOME/test ]
# then
# 	echo "You are the owner of the /etc/passwd file."
# 	date >> $HOME/test
# #
# else
# 	echo "Sorry, you are NOT /etc/passwd file's owner."
# #
# fi



# if [ -G $HOME/test ]
# then
#  	echo "You are in the same default group as"
#  	echo "the $HOME/TestGroupFile file's group."
# #
# else
# 	echo "Sorry, your default group and $HOME/TestGroupFile"
#  	echo "file's group are different."
# # 
# fi


if [ $HOME/Downloads/games.rpm -nt $HOME/software/games.rpm ]
then
	echo "The $HOME/Downloads/games.rpm file is newer"
	echo "than the $HOME/software/games.rpm file."
#
else
	echo "The $HOME/Downloads/games.rpm file is older"
 	echo "than the $HOME/software/games.rpm file."
#
fi
