#!/bin/bash
testuser=christine
if [ $testuser != christine ]
then
 echo "The testuser variable does NOT contain: christine"
else
 echo "The testuser variable contains: christine"
fi
echo outside if-statement
