#!/bin/bash

if (which rpm &> /dev/null)
then
	item_rpm=1
	echo "You have the basic rpm utility"
else
	item_rpm=0
fi

if (which flatpak &> /dev/null)
then
	item_flatpak=1
	echo "You have the flatpak application container."
else
	item_flatpak=0
fi

if (which dnf &> /dev/null)
then
	item_dnfyum=1
	echo "You have the dnf package manager."
elif (which um &> /dev/null)
then
	item_dnfyum=1
	echo "You have the yum package manager."
else
	item_dnfyum=0
fi


((redhatscore=$item_rpm + $item_dnfyum + $item_flatpak))
echo $redhatscore


if (which dpkg &> /dev/null)
then
	item_dpkg=1
	echo "You have the basic dpkg utility."
else
	item_dpkg=0
fi


if (which apt &> /dev/null)
then
        item_aptaptget=1
        echo "You have the basic apt-get utility"
else
        item_aptaptget=0
fi

if (which snap &> /dev/null)
then
        item_snap=1
        echo "You have the snap application container."
else
        item_snap=0
fi


((debianscore=$item_dpkg + $item_aptaptget + $item_snap))

if [ $debianscore -gt $redhatscore ]
then
	echo "Most likely your Linux distribution is Debian-based."
elif [ $redhatscore -gt $debianscore ]
then
	echo "Most likely your Linux distribution is Red Hat-based."
else
	echo "Unable to determine Linux distribution base."
fi


